In [12]:
from tensorflow.keras.preprocessing.text import one_hot

In [13]:
sent=['the glass of milk',
      'the glass of juice',
      'the cup of tea',
      'I am eating glass of milk'
      'I am a good boy',
      'understand the meaning of words']

In [14]:
voc_size=10000

In [15]:
one_hot_rep=[one_hot(words,voc_size)for words in sent]
one_hot_rep

[[8962, 9532, 5816, 6383],
 [8962, 9532, 5816, 5162],
 [8962, 1746, 5816, 2425],
 [9350, 4483, 415, 9532, 5816, 8443, 4483, 7779, 9706, 9590],
 [8676, 8962, 1895, 5816, 6422]]

In [16]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
import numpy as np

In [17]:
sent_length=8
embedded_docs=pad_sequences(one_hot_rep,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 8962 9532 5816 6383]
 [   0    0    0    0 8962 9532 5816 5162]
 [   0    0    0    0 8962 1746 5816 2425]
 [ 415 9532 5816 8443 4483 7779 9706 9590]
 [   0    0    0 8676 8962 1895 5816 6422]]


In [18]:
dim=10

In [21]:
model = Sequential()
model.add(Embedding(voc_size, dim, input_shape=(sent_length,)))
model.compile('adam', 'mse')
model.summary()


d:\Anaconda\envs\dl\lib\site-packages\keras\src\layers\core\embedding.py:100: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [22]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 197ms/step


array([[[-2.21405029e-02, -1.31321326e-02,  4.57098149e-02,
          3.48560326e-02,  4.13683169e-02, -1.34755857e-02,
         -2.34409329e-02,  7.19488785e-03,  2.20189728e-02,
          3.47347520e-02],
        [-2.21405029e-02, -1.31321326e-02,  4.57098149e-02,
          3.48560326e-02,  4.13683169e-02, -1.34755857e-02,
         -2.34409329e-02,  7.19488785e-03,  2.20189728e-02,
          3.47347520e-02],
        [-2.21405029e-02, -1.31321326e-02,  4.57098149e-02,
          3.48560326e-02,  4.13683169e-02, -1.34755857e-02,
         -2.34409329e-02,  7.19488785e-03,  2.20189728e-02,
          3.47347520e-02],
        [-2.21405029e-02, -1.31321326e-02,  4.57098149e-02,
          3.48560326e-02,  4.13683169e-02, -1.34755857e-02,
         -2.34409329e-02,  7.19488785e-03,  2.20189728e-02,
          3.47347520e-02],
        [-3.08199655e-02,  1.77152082e-03,  2.78785117e-02,
         -1.12575293e-02,  5.10804728e-03, -3.54318507e-02,
          4.34906967e-02,  1.64836757e-02,  1.403275

In [23]:
embedded_docs[0]

array([   0,    0,    0,    0, 8962, 9532, 5816, 6383], dtype=int32)

In [26]:
model.predict(embedded_docs[0:1])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step


array([[[-0.0221405 , -0.01313213,  0.04570981,  0.03485603,
          0.04136832, -0.01347559, -0.02344093,  0.00719489,
          0.02201897,  0.03473475],
        [-0.0221405 , -0.01313213,  0.04570981,  0.03485603,
          0.04136832, -0.01347559, -0.02344093,  0.00719489,
          0.02201897,  0.03473475],
        [-0.0221405 , -0.01313213,  0.04570981,  0.03485603,
          0.04136832, -0.01347559, -0.02344093,  0.00719489,
          0.02201897,  0.03473475],
        [-0.0221405 , -0.01313213,  0.04570981,  0.03485603,
          0.04136832, -0.01347559, -0.02344093,  0.00719489,
          0.02201897,  0.03473475],
        [-0.03081997,  0.00177152,  0.02787851, -0.01125753,
          0.00510805, -0.03543185,  0.0434907 ,  0.01648368,
          0.01403276,  0.04312276],
        [ 0.04744731, -0.00474882,  0.02559071, -0.01038433,
          0.01021526, -0.04894077,  0.01797673, -0.00077154,
          0.04967052,  0.00533458],
        [ 0.0454801 ,  0.03811175, -0.04084542,  0.0